export const IDCAPARELATORIO = "IDCAPARELATORIO";
export const IDSUMARIORELATORIO = "IDSUMARIORELATORIO";
export const IDREVISAOCARTEIRA = "IDREVISAOCARTEIRA";
export const IDGRAFICOSREVISAOCARTEIRA = "IDGRAFICOSREVISAOCARTEIRA";
export const IDRETORNODOMES = "IDRETORNODOMES";
export const IDRETORNODOMESRESUMO = "IDRETORNODOMESRESUMO";
